### ISSUE TITLE
About obtaining the data set

### ISSUE THREAD

**Issue by 1solati0n** [Mingrui-Yu/shape_control_DLO#1]
Hello, I read your code and am very interested in this project. I have also recently been studying the operation of cables by a dual-Manipulator robot. Could you please share the method of obtaining the data set?

**Comment by Mingrui-Yu** [comment]
Hi, you can refer to the [journal version of this work](https://mingrui-yu.github.io/shape_control_DLO_2/) for a further improved shape control method and more details, including the description of the data collection method.
